import { languageQueries } from '../queries';
import { LanguageDefinition } from './types';

const FULL_CODE_CAPABILITIES = {
  entities: true,
  imports: true,
  variables: true,
  calls: true,
  comments: true,
} as const;

const METADATA_CAPABILITIES = {
  entities: false,
  imports: false,
  variables: false,
  calls: false,
  comments: false,
} as const;

export const BUILTIN_LANGUAGE_DEFINITIONS: LanguageDefinition[] = [
  {
    id: 'javascript',
    displayName: 'JavaScript',
    adapterId: 'typescript-semantic-adapter',
    parserEngine: 'typescript-semantic',
    supportTier: 'semantic',
    wasmName: 'javascript',
    extensions: ['.js', '.mjs', '.cjs', '.jsx'],
    query: languageQueries.javascript,
    capabilities: FULL_CODE_CAPABILITIES,
  },
  {
    id: 'typescript',
    displayName: 'TypeScript',
    adapterId: 'typescript-semantic-adapter',
    parserEngine: 'typescript-semantic',
    supportTier: 'semantic',
    wasmName: 'typescript',
    extensions: ['.ts', '.mts', '.cts'],
    query: languageQueries.typescript,
    capabilities: FULL_CODE_CAPABILITIES,
  },
  {
    id: 'tsx',
    displayName: 'TSX',
    adapterId: 'typescript-semantic-adapter',
    parserEngine: 'typescript-semantic',
    supportTier: 'semantic',
    wasmName: 'tsx',
    extensions: ['.tsx'],
    query: languageQueries.tsx,
    capabilities: FULL_CODE_CAPABILITIES,
  },
  {
    id: 'python',
    displayName: 'Python',
    adapterId: 'tree-sitter-query-adapter',
    parserEngine: 'tree-sitter',
    supportTier: 'structural',
    wasmName: 'python',
    extensions: ['.py'],
    query: languageQueries.python,
    capabilities: FULL_CODE_CAPABILITIES,
  },
  {
    id: 'go',
    displayName: 'Go',
    adapterId: 'tree-sitter-query-adapter',
    parserEngine: 'tree-sitter',
    supportTier: 'structural',
    wasmName: 'go',
    extensions: ['.go'],
    query: languageQueries.go,
    capabilities: FULL_CODE_CAPABILITIES,
  },
  {
    id: 'rust',
    displayName: 'Rust',
    adapterId: 'tree-sitter-query-adapter',
    parserEngine: 'tree-sitter',
    supportTier: 'structural',
    wasmName: 'rust',
    extensions: ['.rs'],
    query: languageQueries.rust,
    capabilities: FULL_CODE_CAPABILITIES,
  },
  {
    id: 'java',
    displayName: 'Java',
    adapterId: 'tree-sitter-query-adapter',
    parserEngine: 'tree-sitter',
    supportTier: 'structural',
    wasmName: 'java',
    extensions: ['.java'],
    query: languageQueries.java,
    capabilities: FULL_CODE_CAPABILITIES,
  },
  {
    id: 'cpp',
    displayName: 'C/C++',
    adapterId: 'tree-sitter-query-adapter',
    parserEngine: 'tree-sitter',
    supportTier: 'structural',
    wasmName: 'cpp',
    extensions: ['.c', '.cc', '.cpp', '.h', '.hpp'],
    query: languageQueries.cpp,
    capabilities: FULL_CODE_CAPABILITIES,
  },
  {
    id: 'c_sharp',
    displayName: 'C#',
    adapterId: 'tree-sitter-query-adapter',
    parserEngine: 'tree-sitter',
    supportTier: 'structural',
    wasmName: 'c_sharp',
    extensions: ['.cs'],
    query: languageQueries.c_sharp,
    capabilities: FULL_CODE_CAPABILITIES,
  },
  {
    id: 'php',
    displayName: 'PHP',
    adapterId: 'tree-sitter-query-adapter',
    parserEngine: 'tree-sitter',
    supportTier: 'structural',
    wasmName: 'php',
    extensions: ['.php'],
    query: languageQueries.php,
    capabilities: FULL_CODE_CAPABILITIES,
  },
  {
    id: 'ruby',
    displayName: 'Ruby',
    adapterId: 'tree-sitter-query-adapter',
    parserEngine: 'tree-sitter',
    supportTier: 'structural',
    wasmName: 'ruby',
    extensions: ['.rb'],
    query: languageQueries.ruby,
    capabilities: FULL_CODE_CAPABILITIES,
  },
  {
    id: 'zig',
    displayName: 'Zig',
    adapterId: 'tree-sitter-query-adapter',
    parserEngine: 'tree-sitter',
    supportTier: 'structural',
    wasmName: 'zig',
    extensions: ['.zig'],
    query: languageQueries.zig,
    capabilities: FULL_CODE_CAPABILITIES,
  },
  {
    id: 'swift',
    displayName: 'Swift',
    adapterId: 'tree-sitter-query-adapter',
    parserEngine: 'tree-sitter',
    supportTier: 'structural',
    wasmName: 'swift',
    extensions: ['.swift'],
    query: languageQueries.swift,
    capabilities: FULL_CODE_CAPABILITIES,
  },
  {
    id: 'kotlin',
    displayName: 'Kotlin',
    adapterId: 'tree-sitter-query-adapter',
    parserEngine: 'tree-sitter',
    supportTier: 'structural',
    wasmName: 'kotlin',
    extensions: ['.kt', '.kts'],
    query: languageQueries.kotlin,
    capabilities: FULL_CODE_CAPABILITIES,
  },
  {
    id: 'markdown',
    displayName: 'Markdown',
    adapterId: 'markdown-adr-adapter',
    parserEngine: 'markdown-adr',
    supportTier: 'metadata',
    extensions: ['.md'],
    capabilities: METADATA_CAPABILITIES,
  },
  {
    id: 'bash',
    displayName: 'Bash',
    adapterId: 'tree-sitter-query-adapter',
    parserEngine: 'tree-sitter',
    supportTier: 'structural',
    wasmName: 'bash',
    extensions: ['.sh', '.bash'],
    query: languageQueries.bash,
    capabilities: FULL_CODE_CAPABILITIES,
  },
  {
    id: 'html',
    displayName: 'HTML',
    adapterId: 'tree-sitter-query-adapter',
    parserEngine: 'tree-sitter',
    supportTier: 'limited',
    wasmName: 'html',
    extensions: ['.html', '.htm'],
    query: languageQueries.html,
    capabilities: FULL_CODE_CAPABILITIES,
  },
  {
    id: 'css',
    displayName: 'CSS',
    adapterId: 'tree-sitter-query-adapter',
    parserEngine: 'tree-sitter',
    supportTier: 'limited',
    wasmName: 'css',
    extensions: ['.css'],
    query: languageQueries.css,
    capabilities: FULL_CODE_CAPABILITIES,
  },
  {
    id: 'vue',
    displayName: 'Vue',
    adapterId: 'tree-sitter-query-adapter',
    parserEngine: 'tree-sitter',
    supportTier: 'limited',
    wasmName: 'vue',
    extensions: ['.vue'],
    query: languageQueries.vue,
    capabilities: FULL_CODE_CAPABILITIES,
  },
  {
    id: 'yaml',
    displayName: 'YAML',
    adapterId: 'tree-sitter-query-adapter',
    parserEngine: 'tree-sitter',
    supportTier: 'metadata',
    wasmName: 'yaml',
    extensions: ['.yml', '.yaml'],
    query: languageQueries.yaml,
    capabilities: FULL_CODE_CAPABILITIES,
  },
  {
    id: 'json',
    displayName: 'JSON',
    adapterId: 'tree-sitter-query-adapter',
    parserEngine: 'tree-sitter',
    supportTier: 'metadata',
    wasmName: 'json',
    extensions: ['.json'],
    query: languageQueries.json,
    capabilities: FULL_CODE_CAPABILITIES,
  },
];
