import * as fs from 'fs';
import * as path from 'path';
import { KuzuGraphService } from './KuzuGraphService';

export interface SkillTemplate {
  name: string;
  description: string;
  tools: string[];
  resources: string[];
  patterns: string[];
  filePath: string;
}

export class SkillsGenerator {
  private graphService: KuzuGraphService;
  private projectPath: string;

  constructor(projectPath: string) {
    this.projectPath = projectPath;
    this.graphService = new KuzuGraphService(projectPath);
  }

  async init(): Promise<void> {
    await this.graphService.init();
  }

  async generateSkillForNode(nodeId: string): Promise<SkillTemplate> {
    // Get node details
    const nodes = await this.graphService.queryNodes(undefined, nodeId);
    if (nodes.length === 0) {
      throw new Error(`Node not found: ${nodeId}`);
    }

    const node = nodes[0];
    const label = node['n.label'];
    const type = node['n.type'];

    // Get neighbors
    // const neighbors = await this.graphService.queryNeighbors(nodeId);
    
    // Get patterns/anti-patterns
    const patterns = await this.detectPatterns(nodeId);

    const skill: SkillTemplate = {
      name: `codemaps-${label.toLowerCase().replace(/[^a-z0-9]/g, '-')}`,
      description: `Architectural context for ${label} (${type})`,
      tools: [
        'analyze_project',
        'get_graph_context',
        'get_node_dependencies',
        'get_blast_radius',
      ],
      resources: [
        'project_summary',
        'graph_full',
        'agent_project_brain',
      ],
      patterns: patterns,
      filePath: this.getSkillPath(label),
    };

    // Write SKILL.md
    await this.writeSkillFile(skill, nodeId);

    return skill;
  }

  async generateProjectSkills(): Promise<SkillTemplate[]> {
    const skills: SkillTemplate[] = [];
    
    // Get all file nodes
    const result = await this.graphService.queryNodes('file');

    const topLevelFiles = result.filter((f: any) => {
      const path = f['n.filePath'];
      return path && !path.includes('/node_modules/') && !path.includes('/.');
    });

    for (const file of topLevelFiles.slice(0, 10)) {
      try {
        const skill = await this.generateSkillForNode(file['n.id']);
        skills.push(skill);
      } catch (err) {
        console.error(`Failed to generate skill for ${file['n.id']}:`, err);
      }
    }

    return skills;
  }

  private async detectPatterns(nodeId: string): Promise<string[]> {
    const patterns: string[] = [];
    
    // Check for circular dependencies
    const result = await this.graphService.query(`
      MATCH path = (n:FileNode {id: '${nodeId}'})-[:FileEdge*2..3]->(n)
      RETURN length(path) as cycleLength
    `);
    const cycles = await result.getAll();
    
    if (cycles.length > 0) {
      patterns.push('⚠️ Circular dependency detected');
    }

    // Check for high churn
    const neighbors = await this.graphService.queryNeighbors(nodeId);
    if (neighbors.length > 10) {
      patterns.push('🔥 High coupling - consider refactoring');
    }

    return patterns;
  }

  private getSkillPath(label: string): string {
    const skillDir = path.join(this.projectPath, '.claude', 'skills', 'codemaps');
    if (!fs.existsSync(skillDir)) {
      fs.mkdirSync(skillDir, { recursive: true });
    }
    
    const safeName = label.toLowerCase().replace(/[^a-z0-9]/g, '-');
    return path.join(skillDir, `${safeName}-context.md`);
  }

  private async writeSkillFile(skill: SkillTemplate, nodeId: string): Promise<void> {
    const content = `# ${skill.name}

## Description
${skill.description}

## Context
- **Node ID**: ${nodeId}
- **Type**: ${skill.name.split('-').pop()}

## Recommended Tools
${skill.tools.map(t => `- \`${t}\``).join('\n')}

## Available Resources
${skill.resources.map(r => `- \`${r}\``).join('\n')}

## Detected Patterns
${skill.patterns.length > 0 
  ? skill.patterns.map(p => `- ${p}`).join('\n')
  : '- No patterns detected'}

## Usage
This skill is auto-generated by CodeMaps. Update it as the architecture evolves.

Generated: ${new Date().toISOString()}
`;

    fs.writeFileSync(skill.filePath, content);
  }

  async close(): Promise<void> {
    await this.graphService.close();
  }
}
